#
# conda env create -f qplan_conda_environment.yml
#
name: qplan
dependencies:
  - python=3.11
  - pip
  - astropy
  - scipy
  - matplotlib
  - pillow
  - pandas
  - xlrd
  - openpyxl
  - pyqt
  - qtpy
  - ephem
  - python-dateutil
  - pymongo
  - pyyaml
  - git
