#
# conda env create -f qplan_conda_environment.yml
#
name: qplan
dependencies:
  - python=3.11
  - pip
  - astropy
  - skyfield
  - scipy
  - matplotlib
  - pillow
  - joblib
  - pandas
  - xlrd
  - openpyxl
  - pyqt
  - qtpy
  - python-dateutil
  - pymongo
  - pyyaml
  - git
