#
# conda env create -f qplan_conda_environment.yml
#
name: qplan
dependencies:
  - python=3.13
  - pip
  - astropy>=7.2.0
  - scipy
  - matplotlib
  - pillow
  - joblib
  - pandas
  - xlrd
  - openpyxl
  - pyqt
  - qtpy
  - python-dateutil
  - pymongo
  - pyyaml
  - pycairo
  - cairosvg
  - pip

