#!/usr/bin/env python
#
# qplan -- Subaru Telescope Queue Planning Tool
#
"""
Usage:
    qplan --help
    qplan [options] [fitsfile] ...
"""
import sys
from qplan import main, version

if __name__ == "__main__":

    viewer = main.QueuePlanner(layout=main.default_layout)
    viewer.add_plugins(main.plugins)

    # Parse command line options with optparse module
    from optparse import OptionParser

    usage = "usage: %prog [options] cmd [args]"
    optprs = OptionParser(usage=usage,
                          version=('%%prog %s' % version.version))
    viewer.add_default_options(optprs)

    (options, args) = optprs.parse_args(sys.argv[1:])

    if options.display:
        os.environ['DISPLAY'] = options.display

    # Are we debugging this?
    if options.debug:
        import pdb

        pdb.run('viewer.main(options, args)')

    # Are we profiling this?
    elif options.profile:
        import profile

        print(("%s profile:" % sys.argv[0]))
        profile.run('viewer.main(options, args)')

    else:
        viewer.main(options, args)

#END
