#!/usr/bin/env python
#
# qplan -- Subaru Telescope Queue Planning Tool
#
"""
Usage:
    qplan --help
    qplan --version
    qplan [options]
"""
import sys, os
from argparse import ArgumentParser

from qplan import main

if __name__ == "__main__":

    viewer = main.QueuePlanner(layout=main.default_layout)
    viewer.add_plugins(main.plugins)

    argprs = ArgumentParser(description="Queue Planner for Subaru Telescope")
    viewer.add_default_options(argprs)

    (options, args) = argprs.parse_known_args(sys.argv[1:])

    if options.display:
        os.environ['DISPLAY'] = options.display

    viewer.main(options, args)
