name: Lint

on:
  push:
    branches:
    - master
    - 'v*'
    tags:
    - '*'
  pull_request:

# Cancel duplicate builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    name: Lint with ruff
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install ruff
      run: python -m pip install --upgrade pip ruff
    - name: Run ruff
      run: ruff check qplan/
